!coverage.py: This is a private format, don't read it directly!{"lines":{"/home/vsmysle/dev/pyfile.io/fileio/__init__.py":[1,2],"/home/vsmysle/dev/pyfile.io/fileio/api.py":[1,2,3,4,5,6,7,9,10,13,14,16,29,79,100,140,172,199,219,231,243,255,270,22,23,24,25,26,27,41,43,45,47,49,51,52,53,211,216,217,57,62,63,65,66,67,68,69,70,71,91,186,187,188,196,197,92,93,94,280,281,95,229,96,265,266,267,268,97,98,189,191,195,109,111,113,115,117,118,119,127,129,130,131,133,135,114,137,138,116,121,122,151,152,155,159,161,164,165,166,167,156,170,190,192,193],"/home/vsmysle/dev/pyfile.io/fileio/models.py":[1,2,3,6,7,9,27,34,45,49,11,12,14,15,16,17,25,36,37,38,39,40,41,42,47,51],"/home/vsmysle/dev/pyfile.io/fileio/exceptions.py":[1,4,9,10,13,17,18,21,25,26]}}